# Menggunakan image resmi MySQL
FROM mysql:8.0

# Mengatur variabel lingkungan
ENV MYSQL_ROOT_PASSWORD faizin

# Menyalin file SQL ke dalam container
COPY penginapan_id.sql /docker-entrypoint-initdb.d/penginapan_id.sql
